---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: alice
rules:
- apiGroups:
  - ""
  resources:
  - services
  - pods
  - pods/log
  verbs:
  - '*'
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - '*'
- apiGroups:
  - bitnami.com
  resources:
  - sealedsecrets
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - '*'
  resourceNames:
  - logging-api-token
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: alice
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: alice
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: alice
