apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: edit-sealedsecrets
  labels:
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
rules:
- apiGroups:
  - bitnami.com
  resources:
  - sealedsecrets
  verbs:
  - create
  - delete
  - deletecollection
  - patch
  - update
  - get
  - list
  - watch
